"""
Kavach - AI Legal Document Engine for India
PDF Service - WeasyPrint Integration
"""

from weasyprint import HTML, CSS
from typing import Optional
import os
from config import settings


class PDFService:
    """PDF generation service using WeasyPrint"""
    
    def __init__(self):
        """Initialize PDF service"""
        self.upload_dir = settings.UPLOAD_DIR
        self.pdf_dir = os.path.join(self.upload_dir, "pdf")
        
        # Create directories if they don't exist
        os.makedirs(self.pdf_dir, exist_ok=True)
    
    async def generate_pdf(
        self,
        document_id: str,
        html_content: str,
        title: str,
        is_watermarked: bool = False
    ) -> str:
        """
        Generate PDF from HTML content

        Args:
            document_id: Document ID for filename
            html_content: HTML content to convert
            title: Document title
            is_watermarked: Whether to add watermark

        Returns:
            Path to generated PDF file
        """
        try:
            # Build CSS
            css_content = self._get_base_css()

            if is_watermarked:
                css_content += self._get_watermark_css()

            # Generate PDF
            output_filename = f"{document_id}.pdf"
            output_path = os.path.join(self.pdf_dir, output_filename)

            # Wrap HTML content with proper structure
            full_html = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <title>{title}</title>
                <style>{css_content}</style>
            </head>
            <body>
                {html_content}
            </body>
            </html>
            """

            HTML(string=full_html).write_pdf(
                output_path,
                stylesheets=[CSS(string=css_content)]
            )

            return output_path

        except Exception as e:
            raise Exception(f"PDF generation failed: {str(e)}")
    
    def _get_base_css(self) -> str:
        """Get base CSS for document styling"""
        return """
        @page {
            size: A4;
            margin: 25mm;
        }
        
        body {
            font-family: Georgia, serif;
            font-size: 11pt;
            line-height: 1.6;
            color: #000;
        }
        
        h1, h2, h3, h4, h5, h6 {
            font-weight: bold;
            margin-top: 1em;
            margin-bottom: 0.5em;
        }
        
        h1 { font-size: 16pt; }
        h2 { font-size: 14pt; }
        h3 { font-size: 12pt; }
        
        p {
            margin-bottom: 0.5em;
            text-align: justify;
        }
        
        .clause-number {
            font-weight: bold;
        }
        
        .sub-clause {
            margin-left: 20px;
        }
        
        .party-name {
            text-transform: uppercase;
            font-weight: bold;
        }
        
        .signature-block {
            margin-top: 3em;
            page-break-inside: avoid;
        }
        
        .signature-line {
            border-top: 1px solid #000;
            width: 200px;
            margin-top: 2em;
        }
        
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 9pt;
            color: #666;
            padding: 10px;
        }
        
        .disclaimer {
            font-size: 8pt;
            color: #999;
            margin-top: 2em;
            text-align: center;
        }
        """
    
    def _get_watermark_css(self) -> str:
        """Get CSS for watermark"""
        return """
        @page {
            @bottom-center {
                content: "Generated by Kavach — kavachlegal.com";
                font-size: 9pt;
                color: #999;
            }
        }
        
        body::before {
            content: "KAVACH DRAFT";
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            font-size: 72pt;
            color: rgba(0, 0, 0, 0.1);
            z-index: -1;
            pointer-events: none;
        }
        """


# Singleton instance
pdf_service = PDFService()
