"use client"

import { useState } from "react"

const FAQ_ITEMS = [
  {
    q: "Are documents generated by Kavach legally valid in India?",
    a: "Yes. All document templates are drafted with reference to Indian contract law, the Indian Contract Act 1872, and relevant state-specific regulations. Documents include jurisdiction clauses, proper party identification, and consideration terms. We recommend review by a legal professional for high-stakes agreements.",
  },
  {
    q: "Which Indian states are supported for stamp duty calculation?",
    a: "Kavach supports stamp duty rates for 14 Indian states: Maharashtra, Karnataka, Tamil Nadu, Uttar Pradesh, Gujarat, Rajasthan, Delhi, West Bengal, Telangana, Andhra Pradesh, Kerala, Madhya Pradesh, Punjab, and Haryana. More states are being added regularly.",
  },
  {
    q: "What AI model powers document generation?",
    a: "Kavach uses Groq's LPU inference running llama-3.3-70b-versatile as the primary engine. If Groq is unavailable, it automatically falls back to NVIDIA NIM (meta/llama-3.3-70b-instruct). All generation happens via API — no data is used for model training.",
  },
  {
    q: "Can I customise clauses in my document?",
    a: "Absolutely. Pro and Agency subscribers get full access to the Clause Library with 50+ pre-drafted India-specific clauses. You can browse by category, search, preview, and inject clauses into any document. You can also create and save custom clauses for repeated use.",
  },
  {
    q: "How is my data protected?",
    a: "All data is encrypted in transit (TLS 1.3) and at rest. Documents are stored in PostgreSQL with encrypted backups. Payment processing is handled entirely by Razorpay — Kavach never stores card details. We comply with DPDP Act 2023 data protection principles.",
  },
]

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null)

  function toggle(i: number) {
    setOpenIndex(openIndex === i ? null : i)
  }

  return (
    <section id="faq" className="container mx-auto max-w-[1240px] px-8 py-32">
      <div className="mx-auto mb-16 max-w-[600px] text-center">
        <h2 className="mb-5 text-[3.2rem] font-semibold tracking-[-0.04em]">
          Frequently <span className="text-indigo-500 [text-shadow:0_0_20px_rgba(99,102,241,0.4)]">Asked.</span>
        </h2>
        <p className="text-lg font-light leading-relaxed text-slate-400">
          Everything you need to know about using Kavach for your legal documents.
        </p>
      </div>

      <div className="faq-list">
        {FAQ_ITEMS.map((item, i) => (
          <div
            key={i}
            className={`faq-item ${openIndex === i ? "open" : ""}`}
          >
            <button
              className="faq-question"
              onClick={() => toggle(i)}
              aria-expanded={openIndex === i}
            >
              <span>{item.q}</span>
              <span className="faq-toggle">+</span>
            </button>
            <div className="faq-answer">
              <p>{item.a}</p>
            </div>
          </div>
        ))}
      </div>

      <style jsx>{`
        .faq-list {
          max-width: 800px;
          margin: 0 auto;
          display: flex;
          flex-direction: column;
          gap: 1rem;
        }

        .faq-item {
          background: #0a0a12;
          border: 1px solid rgba(255, 255, 255, 0.06);
          border-radius: 12px;
          overflow: hidden;
          transition: border-color 0.3s;
        }

        .faq-item:hover {
          border-color: rgba(99, 102, 241, 0.25);
        }

        .faq-question {
          width: 100%;
          padding: 1.5rem 2rem;
          display: flex;
          justify-content: space-between;
          align-items: center;
          gap: 1rem;
          background: none;
          border: none;
          color: #ffffff;
          font-family: "Plus Jakarta Sans", sans-serif;
          font-size: 1rem;
          font-weight: 500;
          cursor: pointer;
          text-align: left;
          transition: color 0.3s;
        }

        .faq-question:hover {
          color: #818cf8;
        }

        .faq-toggle {
          font-family: "JetBrains Mono", monospace;
          color: #475569;
          font-size: 1.2rem;
          transition: transform 0.3s;
          flex-shrink: 0;
        }

        .faq-item.open .faq-toggle {
          transform: rotate(45deg);
        }

        .faq-answer {
          max-height: 0;
          overflow: hidden;
          transition: max-height 0.3s ease, padding 0.3s ease;
          padding: 0 2rem;
        }

        .faq-item.open .faq-answer {
          max-height: 300px;
          padding: 0 2rem 1.5rem;
        }

        .faq-answer p {
          color: #94a3b8;
          font-size: 0.95rem;
          line-height: 1.7;
          font-weight: 300;
        }
      `}</style>
    </section>
  )
}
